services:
  # 您的 Web 应用服务
  webapp:
    image: onnx-test:latest # 假设您的应用镜像名为 your-python-app
    build: . # 或者通过 build 指令直接从 Dockerfile 构建
    command: sleep infinity
    ports:
      # 将物理机的 8080 端口映射到容器的 8000 端口
      - "5002:5002"
      - "5003:5003"
      - "5004:5004"
      - "5005:5005"
      - "5006:5006"
    volumes:
      # 核心部分：将当前目录 (.) 映射到容器内的 /app 目录
      - .:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # 使用所有可用的 GPU
              capabilities: [ gpu ] # 明确声明需要的是 GPU 能力
